### ISSUE TITLE
suggestion: Entria GraphQL

### ISSUE THREAD

**Issue by jgcmarins** [slicknode/slicknode#1]
- https://github.com/entria/entria-graphql

**Comment by ivome** [comment]
Thank you for the suggestion. While this looks like an interesting project, it cannot really be compared to slicknode. We will be publishing more information on the GraphQL application platform in the coming weeks. You can follow us on [Facebook](https://www.facebook.com/SlicknodeHQ/) or [Twitter](https://twitter.com/SlicknodeHQ) to get updates about the project or sign up for early access: https://www.slicknode.com/ (there is currently only limited availability though...).
