### ISSUE TITLE
Saving Node With Float Returns HTTP 500

### ISSUE THREAD

**Issue by oliverreid** [slicknode/slicknode#18]
Unable to save a node with a Float property. 
Steps to replicate: 
1. Create new module
2. Add node with a name property
3. Deploy 
4. Save an instance of the node - saves ok
5. Update to have a Float property and deploy 
6. Try creating a new instance or update the existing one via the playground - 500 error

example code 
```
type Travel_Location implements Node & TimeStampedInterface {
    createdAt: DateTime!
    lastUpdatedAt: DateTime
    id: ID!
    lat: Float
    long: Float
}
```

**Comment by oliverreid** [comment]
I was creating the instance using the Playground tool, so it looks like the error is in the UI rather than the API

**Comment by ivome** [comment]
I just deployed a new version of the console, this should work there now as well.
