### ISSUE TITLE
lastUpdatedAt is being populated on Node update.

### ISSUE THREAD

**Issue by oliverreid** [slicknode/slicknode#20]
When updating Nodes that implement `TimeStampedInterface` the `lastUpdatedAt` is not updated. 

Steps to replicate: 
1. Create a schema with the node as defined below.
2. Deploy schema 
3. Create and save an instance of the below node.
4. View form the list page
5. Update the text of the node.
6. Confirm in the list page that `lastUpdatedAt` is still `null`
7. Load edit page and hard refresh, check query on network tab of Chrome devTools and confirm `lastUpdatedAt` is null.

``` 
type Travel_Stop implements Node & TimeStampedInterface {
    id: ID!
    text: String! @input(type: TEXTAREA)
    author: User
    trip: Travel_Trip!
    createdAt: DateTime!
    lastUpdatedAt: DateTime
    location: Travel_Location
    photos: [Travel_Media] @relation(path: "Travel_Stop=stop.Travel_Media")
}
```

**Comment by ivome** [comment]
Thanks for filing this bug report 👍 😄 
We just rolled out a bugfix for this for the client projects. If you redeploy your project, this should work now. 
Please reopen if there are still issues.
