### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by JoshuaPoddoku** [slicknode/slicknode#68]
Hey @ivome , I would like to know if there are any plans in adding a license in future.

**Comment by ivome** [comment]
Hey @JoshuaPoddoku, where specifically is the license missing? Slicknode is licensed under the OSL 3.0 license. The project root has a `LICENSE` file which is a symlink to https://github.com/slicknode/slicknode/blob/master/packages/slicknode/LICENSE
The SPDX identifier is configured in the `package.json` files of the individual packages.

**Comment by JoshuaPoddoku** [comment]
Thanks for clarifying Ivo!

![image](https://user-images.githubusercontent.com/31725457/167933952-0ec37692-e8b6-40f1-9c64-e1fdf0623455.png)
As I tried to access the license by clicking [here ](https://github.com/slicknode/slicknode/blob/master/LICENSE)(as shown in the image) - I could only see a `packages/slicknode/LICENSE` and couldn't predict that it has been moved to the packages folder.

**Comment by ivome** [comment]
Thanks for bringing this up. I guess Github doesn't like the Symlink. I duplicated the LICENSE file in the root dir of the project, so that the link should work now.
