### ISSUE TITLE
Install via NPM on windows - Unsuccesful

### ISSUE THREAD

**Issue by RedZepplin** [slicknode/slicknode#73]
Good Evening, 

Been trying for a couple of hours now to try get this to work but installing slicknode via npm, isn't working.

![image](https://user-images.githubusercontent.com/16080866/196051445-885a9d7f-51aa-41f7-8ea6-6f1ca9ad8ead.png)

I'm not sure if we need an msi installer similar to yarn or just need to add a path variable?

**Comment by ivome** [comment]
It looks like the folder where NPM is installing global dependencies is missing in your path. 

Check where they are locacted `npm list -g`, add this location to your `PATH` in the system variables and then try again.
