### ISSUE TITLE
Changing required field to non-required gives error

### ISSUE THREAD

**Issue by char-cole** [slicknode/slicknode#9]
Even if data type is unchanged, gives error:
Project archive could not be validated. Migration failed

**Comment by ivome** [comment]
We just deployed a new version to the cloud that should fix this issue. There was an error with DB constraints not being added when fields were added to existing types. 
This should now work for all new fields. 

To fix existing fields, you could delete the field, deploy and then recreate it. Afterwards everything should work as expected. If you need the data, create a (temporary) secondary field on the same type and loop over the existing nodes to transfer the data to the new field. Afterwards delete the field, recreate it and move the data from the temporary field back to the originally named one. 

This is also fixed for all new projects. The specific transition was added to our test suite. Let me know if there are further issues. 

Thanks again for reporting this!
